### ISSUE TITLE
WARNING: Method definition info(Any...) in module Base at util.jl:334 overwritten...

### ISSUE THREAD

**Issue by jeff-regier** [kmsquire/Logging.jl#38] opened 2016-04-02 20:30 UTC
When I type `import Logging` I get the warning

WARNING: Method definition info(Any...) in module Base at util.jl:334 overwritten in module Logging at /global/homes/j/jregier/.julia/v0.4/Logging/src/Logging.jl:61.

I can understand getting this warning if I were to type `using Logging`, but shouldn't `info` not get overwritten if I instead type `import Logging`?

**Comment by lostanlen** [comment] 2016-04-09 20:12
FYI, this is a duplicate of #27. I don't understand the subtleties of the problem ; I just know that it affects Mocha and would love to see it go away.

**Comment by kmsquire** [comment] 2016-10-07 03:49
Closing as duplicate of #27.  Will continue the discussion there.

**Closed** 2016-10-07 03:49 UTC
